[package]
edition = "2024"
name = "mirrord-mcp-server"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
axum = "0.8"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = {version = "1.0", features = ["full"]}
